### ISSUE TITLE
Distinguish barrier types and difficulty

### ISSUE THREAD

**Issue by mjray** [cyclosm/cyclosm-cartocss-style#549] opened 2021-04-07 10:38 UTC
Is it possible to show different symbols for slalom barriers and those accursed A barriers which obstruct a lot more cycles from passing through? Is it possible to show the width of the gap?

I think both are barrier=cycle_barrier but width:separation only appears for slalom barriers but it is not universal. Representing even bicycle=dismount and bicycle=no on the map for barriers would show extra information already in OSM that would be useful for cyclists, but I am not sure how this would be best shown.

**Comment by Phyks** [comment] 2021-04-07 17:54
Closing as a duplicate of #219. Let's merge these subjects.

**Closed by Phyks** 2021-04-07 17:54 UTC
