### ISSUE TITLE
Bicycle Parking areas are not shown in an adequate way

### ISSUE THREAD

**Issue by lumica89** [cyclosm/cyclosm-cartocss-style#395] opened 2020-06-11 06:08 UTC
Hi, there is an area in my city that is providing a lof of space for bicycle parking. It is tagged as an area with amenity=bicycle in OSM. You could view it here: https://www.cyclosm.org/#map=20/50.91657/11.56848/cyclosm

![2020-06-11_08h04_06](https://user-images.githubusercontent.com/14803373/84350775-3e8e4780-abba-11ea-9041-bab546f1b1f1.png)

Unfortunately it is not rendered in the map as a bicycle parking area, just one icon is rendered. I think here should be shown a much more visible icon, that this area is designated for bicycle parking.

Reference for amenity=bicycle_parking shows that this tag is allowed to be used on areas (https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_parking).

Maybe you could have a look into this.

Thanks,
Martin

**Comment by Phyks** [comment] 2020-06-11 17:32
Hi,

thanks for the report! It should have been done in latest version https://github.com/cyclosm/cyclosm-cartocss-style/commit/35f3466ef87ae93cfc0f77e4853f2dcdd963bde1.

Seems that there is definitely a bug there. We'll investigate.

Best,

**Comment by Florimondable** [comment] 2020-06-11 20:22
I think the issue is just the icon rendered outside of the area.

**Comment by Phyks** [comment] 2020-08-05 13:36
The issue comes from the fact that the marker is placed at the centre of the polygon (outside the polygon). This is fixed by adding a `market-placement: interior` in https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/amenities.mss#L805 but then the text will be off.

openstreetmap-carto moved both `amenities-points` and `amenities-poly` layers into a single one: https://github.com/gravitystorm/openstreetmap-carto/commit/9ce6a3e34be0d0d2af10a8ce29b4019cdec17319. They also use the same SQL query for the labels, reducing duplication https://github.com/gravitystorm/openstreetmap-carto/commit/f2468d14e84239630e2428dde2341a1c126cd95b.

They have this cryptic message https://github.com/gravitystorm/openstreetmap-carto/pull/1349/commits/759f4e205d42b0e980f723c8378555639319c0b9#diff-0abb12fe08393e8ddccd19e688ded6e5R1629-R1630 as well, which might be of interest for us.

We probably need a larger refactor here to account as well for #142 and #360.

**Closed** 2020-08-05 13:48 UTC
Labels: bug
