### ISSUE TITLE
surface=unpaved is ignored

### ISSUE THREAD

**Issue by kimoldfield** [cyclosm/cyclosm-cartocss-style#603] opened 2021-10-09 11:33 UTC
Currently surface=unpaved appears to be ignored.
A reasonable interpretation of surface=unpaved is to treat it like surface=gravel as this is how I've most often seen the tag used in OSM.

A grep of the source suggests this could be done by adding 'unpaved' to the surface for cyclocross condition in views.sql. Specifically changing the line in `views.sql` from

`            WHEN surface IN ('concrete:lanes', 'concrete:plates', 'gravel', 'sett', 'unhewn_cobblestone', 'cobblestone', 'wood', 'compacted', 'fine_gravel', 'woodchips')`

to

`            WHEN surface IN ('concrete:lanes', 'concrete:plates', 'gravel', 'sett', 'unhewn_cobblestone', 'cobblestone', 'wood', 'compacted', 'fine_gravel', 'woodchips', 'unpaved')`

**Comment by Florimondable** [comment] 2021-10-17 16:05
duplicate of #367

**Closed by Florimondable** 2021-10-17 16:05 UTC
