### ISSUE TITLE
Rendering of train stops

### ISSUE THREAD

**Issue by Ivans-Git** [cyclosm/cyclosm-cartocss-style#529] opened 2021-03-11 15:15 UTC
For some reason the halt train stops are more important than the most important train stations in the cities, for example: https://i.imgur.com/ILjK1eK.png
https://www.cyclosm.org/#map=13/43.3463/-8.3939/cyclosm

**Comment by Phyks** [comment] 2021-03-14 14:33
Duplicate of #527.

**Closed by Phyks** 2021-03-14 14:33 UTC
Labels: duplicate

**Comment by Ivans-Git** [comment] 2021-03-15 17:31
> Duplicate of #527.

Curiously if the station attributes are in a building and not in a separate point the station is not even shown...
https://www.openstreetmap.org/#map=19/43.35245/-8.40995&layers=Y
