### ISSUE TITLE
Smoothness = intermediate resulting in solid lines makes cylclOSM unusable for road bike users.

### ISSUE THREAD

**Issue by HeyFlash** [cyclosm/cyclosm-cartocss-style#585] opened 2021-07-03 09:09 UTC
I know that this is a duplicate of Issue #444, but I think this topic is very important and therefore I'd like to re-open it, with some additional explanation.

CyclOSM renders everything that has been tagged with "smoothness = intermediate" as a solid line, regardless of any other tags.
At least in Germany this results in many gravel roads being rendered as solid lines, even if they have explicitly been tagged as gravel roads. Now, one might argue that they should not have been tagged with "smoothness = intermediate" in the first place, but that is how the situation is, and I assume that this is because with the standard OSM renderer other tags take precedence over the smoothness tag. As it is right now, unfortunately CyclOSM is practically unusuable for road bike users in those areas.

Take for example this area: https://www.openstreetmap.org/#map=16/48.7640/9.0929&layers=Y
If you switch between CyclOSM and the standard renderer, you will see the difference. The standard renderer renders all asphalt roads as solid lines, and all gravel roads as dashed lines, which IMO is the expected result. CyclOSM renders them based on the smoothness value alone, resulting in gravel and asphalt roads being indistinguishable.

Now, from the old issue I can see that you are not willing to render as dashed lines based on the smoothness alone, but I think it would be very helpful if you could let other tags take precedence over the smoothness value. As you can see in that area, all the questionable roads have both a "tracktype=grade2" and a "surface=fine_gravel" tag.

My suggestion would be to let tracktype or surface take precedence over the smoothness rating, and only in cases where neither of those exist (or indicate an asphalt road) render intermediate smoothness as a solid line.

**Comment by Florimondable** [comment] 2021-07-03 17:01
Hi

https://wiki.openstreetmap.org/wiki/Key:smoothness
«Asphalt and equivalent that shows signs of maintenance such as patches of repaired pavement, wider cracks (>2 cm), etc. that may cause trouble for racing bikes. The pavement may contain potholes, but these are small, shallow (<3cm deep) and few so they are easily avoided, or the road shows damage due to subsidence (depressions of a scale >50 cm) or heavy traffic (shallow ruts in asphalt caused by trucks in summer). The quality of the surface starts to affect the speed of most passenger cars, so they will slow down to make the ride more comfortable (but still above 50% of the speed they would drive at if the road was smooth). The best unpaved but compacted roads fall in this category. »

As a road and gravel cyclist I understand you point, on a road bike we try to avoid gravel road, even if they are good. (And on a gravel bike we target these fast fine gravel tracks).
We can rethink the priority of tags and there values for the road quality rendering.

**Comment by HeyFlash** [comment] 2021-07-03 17:29
Thank you for the answer,
this indeed confirms that all of those roads have been tagged incorrectly. However, this is really very common around here.

The other (possibly more correct) solution would be to write a bot that fixes the smoothness value based on the tracktype and surface ratings. But that's probably beyond the scope of what you're doing.

I just wanted to add that apart from this issue CyclOSM is really great!

**Comment by matkoniecz** [comment] 2021-08-21 11:25
> apart from this issue CyclOSM is

as mentioned it is problem of invalid data.

CyclOSM is fine and making clear that data is invalid is helpful

> all of those roads have been tagged incorrectly. However, this is really very common around here

Ten it should be fixed

**Comment by matkoniecz** [comment] 2021-08-21 11:27
Though I would recommend taking the worst out of `smoothness` `surface` `tracktype`

1) I have seen more than once `tracktype=grade1 surface=sand` type of tagging, surface is the hardest to confuse while tracktype and smoothness is very often wrong

2) in general false negatives seems better than false positives

**Comment by Phyks** [comment] 2021-08-25 07:01
> I have seen more than once tracktype=grade1 surface=sand type of tagging, surface is the hardest to confuse while tracktype and smoothness is very often wrong

This is a difficult one. In general, you prefer false negatives (every road marked as passable is indeed passable) to false positives. However, this has to be coupled to tagging errors here.

You can consider both:
* the `tracktype=grade1 surface=sand` (tagging issue) for which you prefer to have `surface` having precedence.
* the `smoothness=bad surface=asphalt` (correct tagging) for which you want the `smoothness` to have precedence.

It is, in my opinion, better to show all the subtleties of `surface` tagging through `smoothness`/`tracktype` rather than trying to automatically fix tagging mistakes (conflict between `tracktype` and `surface`).

**Comment by matkoniecz** [comment] 2021-08-25 07:35
> better to show all the subtleties of surface tagging through smoothness/tracktype

If that is viable: then great. Though I tried to design such style more than once and it never worked really well (even for me who designed it), so if I would be doing it again I would try to scale quality of surface to some single scale (influenced primarily by the most problematic attribute)

**Closed** 2021-09-13 19:30 UTC
