### ISSUE TITLE
Treat a living_street as if it has a speed limit

### ISSUE THREAD

**Issue by geozeisig** [cyclosm/cyclosm-cartocss-style#500] opened 2021-01-21 07:36 UTC
Treat a living_street as if it has a speed limit of max 20 km/h.
[Tag:highway=living_street](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dliving_street): _The implicit speed limits set in legislation vary from "walking speed" up to 20 km/h, in some countries, the speed limit is given explicitly on the sign._
If we don't do it that way,  have to add maxspeed to every living_street.

**Comment by Florimondable** [comment] 2021-01-21 09:39
duplicate of #238

**Closed by Florimondable** 2021-01-21 09:39 UTC
