### ISSUE TITLE
[Bug] Living street is rendered as a normal street

### ISSUE THREAD

**Issue by cyper85** [cyclosm/cyclosm-cartocss-style#501] opened 2021-01-21 11:28 UTC
Example:
https://www.cyclosm.org/#map=20/50.96267/11.62231/cyclosm

[Händelweg](https://www.openstreetmap.org/way/24979720) and [Heinrich-Schütz-Weg](https://www.openstreetmap.org/way/24979738#map=18/50.96344/11.62282&layers=N) are tagged as highway=living_street. 

![Legend Living Street (screenshot)](https://user-images.githubusercontent.com/3944963/105345019-02a57100-5be4-11eb-83a1-2f11408c6fea.png)

The legend shows a living street with bold border and light green background. 

![Händelweg (screenshot)](https://user-images.githubusercontent.com/3944963/105345255-52843800-5be4-11eb-8770-de586e17d83f.png)

But the rendering has only a bold border and a white background. Either the legend or the rendering is wrong or missunderstandable.

**Comment by Florimondable** [comment] 2021-01-21 11:33
duplicate of #428 which is a duplicate of #238

**Closed by Florimondable** 2021-01-21 11:33 UTC
