### ISSUE TITLE
Is the lack of contours deliberate?

### ISSUE THREAD

**Issue by ChrisHodgesUK** [cyclosm/cyclosm-cartocss-style#497] opened 2021-01-19 10:33 UTC
Hill shading is all very well, but doesn't do much to indicate steepness.  This is often more of an issue than total climb, and is easily seen from the spacing of the contours.

**Comment by Florimondable** [comment] 2021-01-19 17:27
I agree, duplicate of #157 ;)

**Closed by Florimondable** 2021-01-19 17:27 UTC
