### ISSUE TITLE
blue and grey arrow in same direction

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#389] opened 2020-06-03 16:48 UTC
If bicycle=designated there is a blue and grey arrow going in the same direction
![image](https://user-images.githubusercontent.com/8955390/83664002-b57b7d00-a5c9-11ea-96d3-d484d74aa8e0.png)
https://www.cyclosm.org/#map=20/48.85546/2.36043/cyclosm

- before rue Pavée the rue de Rivoli is bicycle=designated (with blue arrow in same direction as grey arrow)
- after rue Pavée the rue de Rivoli is bicycle=yes (without blue arrow)

**solution**: there should never be a blue arrow when going in the same direction as the grey arrow

this issue may be related to issue #347

**Comment by Florimondable** [comment] 2020-06-03 20:15
How is that a problem ?
I like having both blue and grey, blue for bicycle designated and grey for motor traffic direction.

**Comment by patman37** [comment] 2020-06-04 07:25
I see two reasons against this:
- **clutter** : there is no added information in having blue and grey arrows there. Bicycles can go where there is a grey arrow anyway and the map should not be cluttered with unnecessary signs 
- **consistency** : why add arrows for just for bicycle=designated and not for bicycle=yes ? We could also add blue arrows to all streets then ?

**Comment by Phyks** [comment] 2020-06-04 11:45
`bicycle=designated` is (in theory) very different than `bicycle=yes`:

> The designated value, when used with a mode of transport key, indicates that a route has been specially designated (typically by a government) for use by a particular mode (or modes) of transport.
(https://wiki.openstreetmap.org/wiki/Tag:access%3Ddesignated)

Therefore, one might expect that these are much more cyclable than any other ways. In this case, "Rue de Rivoli" is currently meant for bikes, with no mixing between bicycles and cars etc. Having `bicycle=yes` on Rue de Rivoli is probably a tagging error though, since this is just a duplicate of the default (implicit) access tags, based on the highway value.


Considering "there is no added information in having blue and grey arrows there", there is indeed an added value in having both which is that the traffic is not bicycle only.

I hear the clutter argument though, and maybe we could rework the markers?

**Comment by patman37** [comment] 2020-06-04 12:58
I now understand that a blue arrow can have two distinct meanings :
![image](https://user-images.githubusercontent.com/8955390/83756779-d26a8b80-a66f-11ea-866f-221ce586bb0c.png)
This is rather confusing. It would be better to have a different sign for a bicycle road.

**Comment by Florimondable** [comment] 2020-06-04 13:29
Yes blue arrow alone is for bicycle=designated.
Grey arrow is also needed in case of oneway for car bidirectional for bicycle, like here https://www.cyclosm.org/#map=19/48.84867/2.28203/cyclosm

**Comment by Phyks** [comment] 2020-11-25 20:42
One idea on this, we could replace the blue arrow for bicycle road by a blue outline arrow. We would keep the blue semantic meaning, but make the difference between the two use cases clearer.

**Comment by DerDings** [comment] 2021-03-14 16:29
> 
> 
> I now understand that a blue arrow can have two distinct meanings :
> ![image](https://user-images.githubusercontent.com/8955390/83756779-d26a8b80-a66f-11ea-866f-221ce586bb0c.png)
> This is rather confusing. It would be better to have a different sign for a bicycle road.

Why not completely remove oneway arrows in `oneway:bicycle=no` streets?
`oneway=no` is considered default and drawn without any additional symbols. From a cyclists perspective, `oneway=no` and `oneway:bicycle=no` are the same, so there is no need to put any arrow in this road. 
![grafik](https://user-images.githubusercontent.com/42044179/111075686-821b3680-84e9-11eb-9bc9-4e7e8e0f5b59.png)
Imagine all the "Double way streets for bikes (one way for cars)" symbols would be completely removed [in this example](https://www.cyclosm.org/#map=16/50.0768/8.2507). The map would look a lot neater, while no information is removed (as long as you're not a motorist using cyclosm accidentally).




This way, the blue arrows remain as a symbol for `bicycle=designated` only.



The symbolic would be:

- no arrow: 
cycleable in both directions (either no `oneway` tag, `oneway=no` or `oneway:bicycle=no`)
- gray arrow:
cyclable only in the direction of the arrow
  ~
- two blue antipodal arrows:
`bicycle=designated` in both directions
- blue arrow:
bicycles designated in one direction
  ~
- blue arrow and grey arrow pointing in the same direction:
oneway road designated to cyclists.

**Comment by DerDings** [comment] 2021-03-14 16:29
> Why not completely remove oneway arrows in `oneway:bicycle=no` streets?


I'll make this a separate issue

**Comment by Phyks** [comment] 2021-03-21 14:48
Coming back on this one, and given the clarification in #532, I'm not sure there is much we can do to improve rendering here.

One idea was:
> We could replace the blue arrow for bicycle road (or countraflow bike traffic, eventually) by a blue "outline only" arrow (blue border with white fill). We would keep the blue semantic meaning, but make the difference between the two use cases clearer.

On my side, I don't have much alternative solution coming to mind. Does any of @DerDings @Florimondable @patman37 have a rendering idea to fix the reported issue? Thanks!

**Comment by DerDings** [comment] 2021-03-21 15:54
> 
> 
> I now understand that a blue arrow can have two distinct meanings :
> ![image](https://user-images.githubusercontent.com/8955390/83756779-d26a8b80-a66f-11ea-866f-221ce586bb0c.png)
> This is rather confusing. It would be better to have a different sign for a bicycle road.

It's not for bicycle road only, but for `bicycle=designated`. This may also be a way which has a "cycleway" sign that is not a path but a service way physically.

> 
> 
> Coming back on this one, and given the clarification in #532, I'm not sure there is much we can do to improve rendering here.
> 
> One idea was:
> 
> > We could replace the blue arrow for bicycle road (or countraflow bike traffic, eventually) by a blue "outline only" arrow (blue border with white fill). We would keep the blue semantic meaning, but make the difference between the two use cases clearer.
> 
> On my side, I don't have much alternative solution coming to mind. Does any of @DerDings @Florimondable @patman37 have a rendering idea to fix the reported issue? Thanks!





If this is done, I'd prefer the designated arrow to remain filled and the _Double way streets for bikes (one way for cars)_ to use the blue outline.

**Reasons:**

filled for `bicycle=designated` | outline only for `oneway:bicycle=no`
---------------------------------|----------------------------------
better visibility atop of blue bicycle roads  | the fill could be grey, so it matches the other arrow
much blue = important bicycle feature | as stated in [this comment](https://github.com/cyclosm/cyclosm-cartocss-style/issues/532#issuecomment-803552587), it is an anti-feature for cyclists, so should use the lesser blue sign
is often part of the main cycle network, so the icon should be drawable also on mid zoom (>= z15) | is only important in subsidiary, narrow roads, so the symbol can be more complicated as it is not necessary to show this at mid and low zoom (< z16 or even < z17)
_ | is currently too prominent in my opinion (#532), so reducing the amount of color will be good to make it less catchy


Additionally, _Double way streets for bikes (one way for cars)_ should use the `@mixed` color, like `shared_lane` does.

**Comment by DerDings** [comment] 2021-03-21 15:59
Or use a stikethrough arrow ![oneway-striked](https://user-images.githubusercontent.com/42044179/111911514-34ad4500-8a66-11eb-94db-cfea61d393d7.png) for `oneway:bicycle=no`. But I see it is not that easy to decipher this symbol, so I'd stick with the previous idea.

**Comment by Florimondable** [comment] 2021-03-21 17:12
Outline arrow is a good idea (can be difficult to do though, arrow are small).
Other shape idea :
- triangle for designated direction
- a shape "->" with no triangle as the head of the arrow but ">".

**Comment by patman37** [comment] 2021-03-21 18:10
I could imagine to keep the blue arrow for double way streets (oneway for cars) and use sharrows for a bicycle designated road :
![image](https://user-images.githubusercontent.com/8955390/111915772-3aac2180-8a78-11eb-8b9a-d3908d50c46b.png)

**Comment by DerDings** [comment] 2021-03-21 19:18
> 
> 
> I could imagine to keep the blue arrow for double way streets (oneway for cars) and use sharrows for a bicycle designated road :
> ![image](https://user-images.githubusercontent.com/8955390/111915772-3aac2180-8a78-11eb-8b9a-d3908d50c46b.png)

This looks really good. nevertheless the _double way streets (oneway for cars)_ should become lighter, like the shared lanes.

**Comment by Phyks** [comment] 2021-03-21 19:38
I like the sharrows idea for designated bicycle road! This could be a nice trick.

@DerDings Regarding the double way streets (oneway for cars), and building on the https://www.google.fr/maps/@48.8385989,2.3515876,3a,75y,283.77h,77.27t/data=!3m6!1e1!3m4!1sPNc6NwTJaPExAl4mmQ-1Nw!2e0!7i16384!8i8192 example from #532, although this infrastructure seems quite bad on paper, it can actually have a huge interest for cyclist. These are major features (at least in France), and should not be minimized.

Compare an extract of a route going from one side to the other. You can go in a straightforward (and quite comfortable, actually) way through these countraflows: http://brouter.de/brouter-web/#map=17/48.83962/2.35495/cyclosm,Waymarked_Trails-Cycling&lonlats=2.362125,48.840472;2.347877,48.839582.
Without them and sticking to regular bicycle infrastructure makes quite a detour: http://brouter.de/brouter-web/#map=17/48.83900/2.35548/cyclosm,Waymarked_Trails-Cycling&lonlats=2.362125,48.840472;2.347877,48.839582&nogos=2.352609,48.838512,57.

The only case where I can imagine we could make the render lighter is when countraflow is indeed done through a regular bicycle infrastructure. This boils down to https://github.com/cyclosm/cyclosm-cartocss-style/issues/260.

**Comment by Phyks** [comment] 2021-03-22 17:35
Test implementation of sharrows is done in https://github.com/cyclosm/cyclosm-cartocss-style/pull/542.

**Comment by Florimondable** [comment] 2021-03-22 21:26
About the two way bicycle arrows, there is may be too much, we could reduce the density.

**Closed** 2021-07-22 18:15 UTC
Labels: pending
