### ISSUE TITLE
still some UTF-8 characters missing

### ISSUE THREAD

**Issue by patman37** [cyclosm/cyclosm-cartocss-style#563] opened 2021-05-04 08:38 UTC
There are still some utf-8 characters not shown in cyclosm. The country name of Mongolia (I guess) is not shown in Mongolian
cyclosm view : https://www.cyclosm.org/#map=5/48.400/103.755/cyclosm
![image](https://user-images.githubusercontent.com/8955390/116978730-66036c80-acc4-11eb-852b-bb0dcd8824d3.png)

standard OpenStreetMap view : https://www.openstreetmap.org/#map=5/45.042/96.855
![image](https://user-images.githubusercontent.com/8955390/116978667-508e4280-acc4-11eb-8e79-81aa5fc87198.png)

this issue may be related to #241

**Comment by Florimondable** [comment] 2021-05-06 20:17
Duplicate of #489 ;)

**Closed by Florimondable** 2021-05-06 20:17 UTC

**Comment by Phyks** [comment] 2021-05-15 15:58
See https://github.com/cyclosm/cyclosm-cartocss-style/blob/master/CHANGELOG.md, the latest changes have not yet been deployed. It will be deployed soon.
