### ISSUE TITLE
Very difficult to distinguish bicycle road from the combination of 30km/h and cycle route

### ISSUE THREAD

**Issue by brainwad** [cyclosm/cyclosm-cartocss-style#405] opened 2020-07-09 09:20 UTC
According to the key, a "cycle street" has colour #7eaeff. But the colours of streets with both 30km/h speed limit and a lcn/rcn cycle route are very similar: #99b5f4 for RCN and #84b5f4 for LCN. I cannot distinguish these - the contrast ratio between the RCN+30 colour and cycle street is 1.09, and between LCN+30 and cycle street it's 1.05 (e.g. https://contrastchecker.com/?c=7eaefF&b=84b5f4). This also has the side-effect of making it really hard to distinguish the tiers of cycle network when both go over 30 km/h streets.

Maybe instead of layering the speed limit and cycle route colours on top of each other, they can striped? Or at zoom levels where speed limits are drawn, the cycle route could be indicated using the road border instead of the fill? Or a centreline?  

Real life example: https://imgur.com/a/17WIhwH

**Comment by Phyks** [comment] 2020-07-17 11:15
It is somewhat voluntary that cycle routes fade away at high zoom levels. At these zoom levels, we want to focus on the real infrastructure on ground rather than the routes. Plus, having similar colors boils down to the fact that we want to keep as much color range as possible for the rest of the (many) details.

CyclOSM is a digital map, so we came up with this compromise where the LCN/RCN routes can be tracked by zooming up/down regularly.

I am afraid that striping them would make too much clutter and difficult to differentiate from paved/unpaved.

We welcome of course any better option for rendering these that you might have!

Best,

**Comment by brainwad** [comment] 2020-07-17 11:18
Then maybe the colour of cycle street should be changed, so its colour is distinguishable from cycle network + 30km/h? perhaps make cycle street a more saturated blue, like cycle paths?

**Comment by brainwad** [comment] 2020-07-17 14:35
Actually maybe cycle streets should just be styled exactly the same as "bicycle road" in the key, i.e. with frequent blue arrows, plus the appropriate 30km/h / 20km/h / vehicle-free colouring? After all, a "cycle street" is just a normal street with low speed limit that is designated by sign for bicycles, so it should be equivalent to `highway=residential bicycle=designated maxspeed=X motor_vehicle=Y` (X and Y dependent on exact signage).

**Comment by Phyks** [comment] 2021-02-18 17:29
Closing as a duplicate of https://github.com/cyclosm/cyclosm-cartocss-style/issues/495.

**Closed by Phyks** 2021-02-18 17:29 UTC
