### ISSUE TITLE
Render smoothness=excellent in a solid line

### ISSUE THREAD

**Issue by geozeisig** [cyclosm/cyclosm-cartocss-style#515] opened 2021-02-11 06:58 UTC
I wonder that smoothness=excellent ( + highway=path + bicycle=designated +foot=designated) is shown as a dashed line.

![smothness-segregated-yes-road](https://user-images.githubusercontent.com/17127509/107608659-de660e80-6c3c-11eb-9bd8-6552ffdcaf75.png)
I would expect a solid line like surface=asphalt.
![surface-segregated-yes-road](https://user-images.githubusercontent.com/17127509/107608923-aad7b400-6c3d-11eb-9cd8-36784ee008f0.png)
I did a [test](https://www.openstreetmap.org/#map=17/32.40599/9.93298&layers=Y) to get snapshots for graphics and it caught my eye. Most of the time, smoothness and surface is used at the same time, but there are [exceptions](https://www.openstreetmap.org/way/240420042#map=16/52.2293/11.5081&layers=Y).

**Comment by Florimondable** [comment] 2021-02-11 17:32
Duplicate of #483 fixed by #498, will be in the next release.

Please clean your test, if you need information between tags and render style you can ask.

**Closed** 2021-02-11 17:33 UTC
